//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirPlanTbl
    {
        public int AirPlanId { get; set; }
        public string AirPlanName { get; set; }
        public int AirPlanCompany { get; set; }
        public int AirPlanCapacity { get; set; }
        public System.DateTime AirPlanCreatedDateTime { get; set; }
        public string AirPlanCode { get; set; }
        public string AirPlanPhoto { get; set; }
    }
}
