//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorldSkillsAirPlanDbEntities : DbContext
    {
        public WorldSkillsAirPlanDbEntities()
            : base("name=WorldSkillsAirPlanDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AirPlanTbl> AirPlanTbls { get; set; }
        public virtual DbSet<LoginLogTbl> LoginLogTbls { get; set; }
        public virtual DbSet<LogOutTbl> LogOutTbls { get; set; }
        public virtual DbSet<MainUserTbl> MainUserTbls { get; set; }
        public virtual DbSet<RullTbl> RullTbls { get; set; }
        public virtual DbSet<UsersTbl> UsersTbls { get; set; }
    }
}
