//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTbl
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserLastName { get; set; }
        public string UserPassword { get; set; }
        public int UserRull { get; set; }
        public int UserStatus { get; set; }
        public string UserNameForProgram { get; set; }
        public System.DateTime UserBirhtday { get; set; }
        public string UserPhoto { get; set; }
    }
}
